services:
  - type: web
    name: hooked-on-phonics
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
